### PR TITLE
fix: rke2 registration token generated twice

### LINKED ISSUE #233: RKE2 registration token inconsistency between 1st CP and following nodes
**What happened:**

When using CAPRKE2 with CAPO there is an issue where the registration token on the 1st CP machine differs to that of the following CP machine or the worker machines. This results in a failure to join the new nodes to cluster with a 401 not authorised

**What did you expect to happen:**
Expectation is that the nodes are able to join the cluster with the correct token.

**How to reproduce it:**

**Anything else you would like to add:**

See [sylva downstream issue](https://gitlab.com/sylva-projects/sylva-core/-/issues/832) for more detail.

**Environment:**

- rke provider version:
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by salasberryfin**
**What this PR does / why we need it**:

The RKE2 Config controller is creating the registration token twice (intermittently) and updating the secret that contains the token so different nodes are trying to get registered with different tokens and failing to do so.

We must ensure [this secret](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/c69285302e9d3733559f65a2ef8031935e0144e4/bootstrap/internal/controllers/rke2config_controller.go#L337) is created once and its value remains unedited so that nodes can be registered to the cluster.

This initial proposal suggests detecting if the secret exists and skip token creation if it does.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #233 

**Special notes for your reviewer**:

We should add test cases that cover the logic of this controller: #https://github.com/rancher-sandbox/cluster-api-provider-rke2/issues/235 tracks this follow-up issue.

**Checklist**:

- [x] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

File: bootstrap/internal/controllers/rke2config_controller.go [hunk 1]
```diff
@@ -334,14 +334,28 @@ func (r *RKE2ConfigReconciler) handleClusterNotInitialized(ctx context.Context,
...
+	// RKE2 server token must only be generated once, so all nodes join the cluster with the same registration token.
+	var token string
 
-		return ctrl.Result{}, err
+	tokenSecret := &corev1.Secret{}
+	secretKey := types.NamespacedName{
+		Namespace: scope.Config.Namespace,
+		Name:      bsutil.TokenName(scope.Cluster.Name),
 	}
+	err := r.Client.Get(ctx, secretKey, tokenSecret)
```
Comment (tmmorin) [inline bootstrap/internal/controllers/rke2config_controller.go:345]: I'm under the impression that this code might be subject to a race condition ; for instance in the case where we would run multiple replicas of the controller (both controller could fail the get in the same window of time before any reaches the create, and then both would do the create).

I think that the right pattern here would be to:
- try to create
- if this fails because the object already exists, then read it's content

Maybe one possibility is to make this update step of createOrUpdateSecretFromObject optional:
https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/main/bootstrap/internal/controllers/rke2config_controller.go#L827-L829

and call createOrUpdateSecretFromObject from generateAndStoreToken with this update step disabled

Comment (salasberryfin) [reply bootstrap/internal/controllers/rke2config_controller.go:345]: Thanks for the feedback @tmmorin. My initial idea was to create a separate `createSecretFromObject` and call this function to generate the token, so that the update functionality is not altered and we don't have to deal with the value being updated, but decided to opt for this simpler solution. Didn't think about the corner case you described. I'll review this and take the other approach.

**Comment by salasberryfin** [comment]
PR is now updated based on review feedback. Current logic will:
- Try to create secret and store registration token.
- If secret already exists, retrieve registration token value.

File: bootstrap/internal/controllers/rke2config_controller.go (hunk 1 above)
Comment (tmmorin) [reply bootstrap/internal/controllers/rke2config_controller.go]: Thanks for solving this problem.

**Review by Danil-Grigorev — APPROVED** [review]
lgtm

**Review by richardcase — APPROVED** [review]
Tested this locally and i didn't see the same duplicate token creation.

**Review by alexander-demicev — APPROVED** [review]
